### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JuanSaenz89** [IMRZ/tww-interactive-map#63]
Hey, I'm a Jr. Developer and Warhammer fan, i really liked your map and whas hoping to do the same for tww-3, is there a way we can talk to better understand how your code works??

**Comment by IMRZ** [comment]
Hi @JuanSaenz89, lately I haven't been actively working on my projects. But I'm happy to answer any questions you have. Are you available on discord? My handle is `.bombardier`. Or if you prefer any other means of communication let me know how to reach you. Thanks.

**Comment by JuanSaenz89** [comment]
Thanks for the answer, i'm available on discord, my handle is `lordpatan` .
